version: '3.1'
services:
  base:
    build: ./base
    image: scoop_base
    deploy:
      replicas: 0
      restart_policy:
        condition: none
 
  broker:
    depends_on:
      - base
    build: ./broker
    image: scoop_broker
    secrets:
      - ssh_client_rsa_key
      - ssh_client_rsa_key.pub
      - ssh_host_rsa_key.pub
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  worker:
    depends_on:
      - base
    build: ./worker
    image: scoop_worker
    secrets:
      - source: ssh_host_rsa_key
        mode: 0400
      - source: ssh_host_rsa_key.pub
        mode: 0444
      - source: ssh_client_rsa_key.pub
        mode: 0444
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker

  root_worker:
    depends_on:
      - worker
    image: scoop_worker
    ports:
      - "8000:8000"
    secrets:
      - source: ssh_host_rsa_key
        mode: 0400
      - source: ssh_host_rsa_key.pub
        mode: 0444
      - source: ssh_client_rsa_key.pub
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
   
  
secrets:
  ssh_client_rsa_key:
    file: secrets/ssh_client_rsa_key
  ssh_client_rsa_key.pub:
    file: secrets/ssh_client_rsa_key.pub
  ssh_host_rsa_key:
    file: secrets/ssh_host_rsa_key
  ssh_host_rsa_key.pub:
    file: secrets/ssh_host_rsa_key.pub
